### PR TITLE
fix: product-card

### LINKED ISSUE #5: ProductCard => storybook
- noNameTafg ??
- utiliser ClassName ???
- +prop price
- react-icons

### PR DESCRIPTION
**Pull request by wassim-arfa**
Fixes #5

### CODE REVIEW

File: components/product/product-card.tsx [hunk 1]
```diff
@@ -40,29 +39,21 @@ export default function ProductCard({ product }: Props) {
...
-          height="20"
-        >
-          <path
-            strokeLinecap="round"
-            strokeLinejoin="round"
-            strokeWidth="1.5"
-            d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"
-          />
-        </svg>
+        <AiOutlineShoppingCart size={'20px'} />
```
Comment (arfa) [inline components/product/product-card.tsx:56]: `size={20}
`par default `px`
